version: "3"
services:

  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - dba_hell_network

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    networks:
      - dba_hell_network
    depends_on:
      - rabbit1
      - postgres

  writer:
    build:
      context: ./writer
      dockerfile: Dockerfile
    networks:
      - dba_hell_network
    depends_on:
      - rabbit1
      - postgres

  postgres:
    restart: always
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dba-test
      - POSTGRES_USER=dba-test
      - POSTGRES_DB=dba_test
    networks:
      - dba_hell_network
    volumes:
      - ./postgres/dba-hell.sql:/docker-entrypoint-initdb.d/dba-hell.sql
      - ./postgres/data:/var/lib/postgresql/data

networks:
  dba_hell_network:
